#use bank;
#select * from deposit;
#select * from borrow;
#select * from customer;
#select * from branch;
#select actno,amount from deposit;
#select cname,actno from deposit;
#select cname from customer;
#select bname from branch;
#select cname from borrow;
#select cname from customer where city="nagpur";
#select cname from deposit where amount>4000;
#select adate from deposit where cname="ANIL";
#select bname from branch where city="bombay";
#select cname from borrow where loanno="L206";
#select cname from deposit where bname="VRCE";
#select bname from branch where city="delhi";
#select cname from deposit where adate="1995-09-05";
#select actno,amount from deposit where adate between  '1995-03-01' and '1995-12-17';
#select city from branch where bname="KAROLBAGH";
#select * from deposit where cname="ANIL";